### ISSUE TITLE
[Logo / Icon]

### ISSUE THREAD

**Issue by pablowbk** [chingu-voyages/v9-geckos-team-04#24]
Choose an Icon for the browser tab

**Comment by pablowbk** [comment]
#1 
![image](https://user-images.githubusercontent.com/36734796/59963884-8f9bbc00-94cf-11e9-9f27-24f15c4ba09e.png)

**Comment by pablowbk** [comment]
#2 
![image](https://user-images.githubusercontent.com/36734796/59964048-ae9b4d80-94d1-11e9-8b06-e4bbf6ef826e.png)

**Comment by Hemlatab** [comment]
#1 This looks good to me
